"""initial schema

Revision ID: 2878e05c33fc
Revises: 
Create Date: 2026-06-24 07:30:42.795303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2878e05c33fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_spend',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=500), nullable=True),
    sa.Column('marketplace', sa.String(length=20), nullable=True),
    sa.Column('spend', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('sales_attributed', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('acos', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_spend_campaign_id'), 'ad_spend', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_spend_date'), 'ad_spend', ['date'], unique=False)
    op.create_index(op.f('ix_ad_spend_marketplace'), 'ad_spend', ['marketplace'], unique=False)
    op.create_index(op.f('ix_ad_spend_platform'), 'ad_spend', ['platform'], unique=False)
    op.create_table('daily_pnl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sales', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('cogs', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('ad_spend', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('ad_spend_sp', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('ad_spend_sb', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('ad_spend_sd', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('ad_spend_sv', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('selling_fees', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('operational_fees', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('refunds', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('reimbursements', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit_no_reimb', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit_with_reimb', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('margin_pct', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('sales_usd', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit_usd', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fx_rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'channel', name='uq_daily_pnl_date_channel')
    )
    op.create_index(op.f('ix_daily_pnl_channel'), 'daily_pnl', ['channel'], unique=False)
    op.create_index(op.f('ix_daily_pnl_date'), 'daily_pnl', ['date'], unique=False)
    op.create_table('financial_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_group_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_id', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('fee_type', sa.String(length=100), nullable=True),
    sa.Column('fee_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_events_asin'), 'financial_events', ['asin'], unique=False)
    op.create_index(op.f('ix_financial_events_event_group_id'), 'financial_events', ['event_group_id'], unique=False)
    op.create_index(op.f('ix_financial_events_event_type'), 'financial_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_financial_events_fee_type'), 'financial_events', ['fee_type'], unique=False)
    op.create_index(op.f('ix_financial_events_marketplace_id'), 'financial_events', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_financial_events_order_id'), 'financial_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_financial_events_posted_date'), 'financial_events', ['posted_date'], unique=False)
    op.create_index(op.f('ix_financial_events_sku'), 'financial_events', ['sku'], unique=False)
    op.create_table('raw_api_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pulled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_api_log_pulled_at'), 'raw_api_log', ['pulled_at'], unique=False)
    op.create_index(op.f('ix_raw_api_log_source'), 'raw_api_log', ['source'], unique=False)
    op.create_table('shopify_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_tax', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_discounts', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_sales_date'), 'shopify_sales', ['date'], unique=False)
    op.create_index(op.f('ix_shopify_sales_order_id'), 'shopify_sales', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_sales_order_id'), table_name='shopify_sales')
    op.drop_index(op.f('ix_shopify_sales_date'), table_name='shopify_sales')
    op.drop_table('shopify_sales')
    op.drop_index(op.f('ix_raw_api_log_source'), table_name='raw_api_log')
    op.drop_index(op.f('ix_raw_api_log_pulled_at'), table_name='raw_api_log')
    op.drop_table('raw_api_log')
    op.drop_index(op.f('ix_financial_events_sku'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_posted_date'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_order_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_marketplace_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_fee_type'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_type'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_group_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_asin'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index(op.f('ix_daily_pnl_date'), table_name='daily_pnl')
    op.drop_index(op.f('ix_daily_pnl_channel'), table_name='daily_pnl')
    op.drop_table('daily_pnl')
    op.drop_index(op.f('ix_ad_spend_platform'), table_name='ad_spend')
    op.drop_index(op.f('ix_ad_spend_marketplace'), table_name='ad_spend')
    op.drop_index(op.f('ix_ad_spend_date'), table_name='ad_spend')
    op.drop_index(op.f('ix_ad_spend_campaign_id'), table_name='ad_spend')
    op.drop_table('ad_spend')
    # ### end Alembic commands ###
