"""widen daily_pnl margin_pct to handle pathological values

Revision ID: afd15f401d7a
Revises: bbaef56cdb7a
Create Date: 2026-06-26 12:16:29.812401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd15f401d7a'
down_revision: Union[str, None] = 'bbaef56cdb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_pnl', 'margin_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_pnl', 'margin_pct',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
