"""add product_cogs and currency_rates

Revision ID: b5460a467ac7
Revises: 2878e05c33fc
Create Date: 2026-06-24 07:49:24.868113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5460a467ac7'
down_revision: Union[str, None] = '2878e05c33fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'effective_date', name='uq_currency_rates_from_to_date')
    )
    op.create_index(op.f('ix_currency_rates_effective_date'), 'currency_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_currency_rates_from_currency'), 'currency_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_currency_rates_to_currency'), 'currency_rates', ['to_currency'], unique=False)
    op.create_table('product_cogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('unit_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('product_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_cogs_asin'), 'product_cogs', ['asin'], unique=False)
    op.create_index(op.f('ix_product_cogs_effective_date'), 'product_cogs', ['effective_date'], unique=False)
    op.create_index(op.f('ix_product_cogs_marketplace'), 'product_cogs', ['marketplace'], unique=False)
    op.create_index(op.f('ix_product_cogs_sku'), 'product_cogs', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_cogs_sku'), table_name='product_cogs')
    op.drop_index(op.f('ix_product_cogs_marketplace'), table_name='product_cogs')
    op.drop_index(op.f('ix_product_cogs_effective_date'), table_name='product_cogs')
    op.drop_index(op.f('ix_product_cogs_asin'), table_name='product_cogs')
    op.drop_table('product_cogs')
    op.drop_index(op.f('ix_currency_rates_to_currency'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_from_currency'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_effective_date'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
