"""add category to financial_events and unmapped_line_items table

Revision ID: bbaef56cdb7a
Revises: b5460a467ac7
Create Date: 2026-06-25 17:50:44.696665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbaef56cdb7a'
down_revision: Union[str, None] = 'b5460a467ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unmapped_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('line_item_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_endpoint', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmapped_line_items_event_type'), 'unmapped_line_items', ['event_type'], unique=False)
    op.create_index(op.f('ix_unmapped_line_items_line_item_name'), 'unmapped_line_items', ['line_item_name'], unique=False)
    op.create_index(op.f('ix_unmapped_line_items_marketplace_id'), 'unmapped_line_items', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_unmapped_line_items_posted_date'), 'unmapped_line_items', ['posted_date'], unique=False)
    op.add_column('financial_events', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('financial_events', sa.Column('raw_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('financial_events', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_financial_events_category'), 'financial_events', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_events_category'), table_name='financial_events')
    op.drop_column('financial_events', 'quantity')
    op.drop_column('financial_events', 'raw_amount')
    op.drop_column('financial_events', 'category')
    op.drop_index(op.f('ix_unmapped_line_items_posted_date'), table_name='unmapped_line_items')
    op.drop_index(op.f('ix_unmapped_line_items_marketplace_id'), table_name='unmapped_line_items')
    op.drop_index(op.f('ix_unmapped_line_items_line_item_name'), table_name='unmapped_line_items')
    op.drop_index(op.f('ix_unmapped_line_items_event_type'), table_name='unmapped_line_items')
    op.drop_table('unmapped_line_items')
    # ### end Alembic commands ###
